# Generated by Django 2.1.7 on 2019-06-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dorsualEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectionID', models.CharField(max_length=500)),
                ('documentID', models.CharField(max_length=500)),
                ('regionID', models.CharField(max_length=500)),
                ('documentTitle', models.CharField(max_length=200)),
                ('dorsualType', models.CharField(max_length=200)),
                ('imageSource', models.CharField(max_length=500)),
                ('judgement', models.BooleanField()),
            ],
        ),
    ]
