# Generated by Django 2.1.7 on 2019-06-08 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dorsual', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dorsualentry',
            name='id',
        ),
        migrations.AddField(
            model_name='dorsualentry',
            name='docAndRegion',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dorsualentry',
            name='regionID',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
