# Generated by Django 2.1.7 on 2019-06-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorsual', '0002_auto_20190608_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorsualentry',
            name='docAndRegion',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dorsualentry',
            name='regionID',
            field=models.CharField(max_length=500),
        ),
    ]
