# Generated by Django 2.2.dev20180620194643 on 2018-10-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NormEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryNo', models.IntegerField(default=0)),
                ('orig_name', models.CharField(max_length=200)),
                ('norm_name', models.CharField(max_length=200)),
            ],
        ),
    ]
