# Generated by Django 2.2.dev20180620194643 on 2018-10-23 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linking', '0002_missingentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MissingEntry',
        ),
    ]
