# Generated by Django 2.2.dev20180620194643 on 2018-10-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linking', '0003_delete_missingentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=200)),
                ('doc', models.CharField(max_length=200)),
                ('ref', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
            ],
        ),
    ]
